# Generated by Django 4.1 on 2023-04-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('idclub', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flarm',
            fields=[
                ('numero_f', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('id_radio', models.CharField(max_length=20)),
                ('id_lcc', models.CharField(max_length=20)),
                ('firmware', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('idinscription', models.AutoField(primary_key=True, serialize=False)),
                ('typeassurance', models.CharField(max_length=100)),
                ('caution', models.BooleanField(default=True)),
                ('cotisation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('forfait_saison', models.BooleanField(default=False)),
                ('stage', models.BooleanField(default=False)),
                ('fcfvv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_personne', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('alive', models.BooleanField(default=True)),
                ('telephone', models.IntegerField()),
                ('gsm', models.IntegerField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('niss', models.BooleanField(default=True)),
                ('idclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.club')),
                ('idinscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.inscription')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Planeur',
            fields=[
                ('id_planeur', models.IntegerField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('biplace', models.BooleanField()),
                ('proprietaire', models.CharField(max_length=255)),
                ('alive', models.BooleanField()),
                ('tmg', models.BooleanField()),
                ('sl', models.BooleanField()),
                ('prix_moteur', models.FloatField()),
                ('dto', models.BooleanField()),
                ('numerof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.flarm')),
            ],
        ),
        migrations.CreateModel(
            name='TypeLicense',
            fields=[
                ('idtypel', models.AutoField(primary_key=True, serialize=False)),
                ('trouillard', models.BooleanField()),
                ('pilote', models.BooleanField()),
                ('pilotetmg', models.BooleanField()),
                ('piloteavion', models.BooleanField()),
            ],
            options={
                'db_table': 'typelicense',
            },
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id_vol', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('ratio', models.FloatField()),
                ('lancer', models.IntegerField()),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('ticket', models.BooleanField()),
                ('tn', models.CharField(max_length=255)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('pmr', models.BooleanField()),
                ('towplane_max_alt', models.FloatField()),
                ('temps_moteur', models.FloatField()),
                ('id_planeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.planeur')),
                ('implique', models.ManyToManyField(to='Encodage_pilote.personne')),
            ],
        ),
        migrations.CreateModel(
            name='TypePersonne',
            fields=[
                ('id_type_p', models.IntegerField(primary_key=True, serialize=False)),
                ('instr_remorque', models.BooleanField(default=False)),
                ('instr_treuil', models.BooleanField(default=False)),
                ('lacher_remorque', models.BooleanField(default=False)),
                ('treuillard', models.BooleanField(default=False)),
                ('passager', models.BooleanField(default=False)),
                ('pilote', models.BooleanField(default=False)),
                ('eleve', models.BooleanField(default=False)),
                ('pilote_avion', models.BooleanField(default=False)),
                ('pmr', models.BooleanField(default=False)),
                ('honneur', models.BooleanField(default=False)),
                ('peutetre', models.ManyToManyField(to='Encodage_pilote.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('idlog', models.AutoField(primary_key=True, serialize=False)),
                ('dateheure', models.DateTimeField(auto_now_add=True)),
                ('qui', models.CharField(max_length=100)),
                ('ordinateur', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('id_personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id_lieu', models.AutoField(primary_key=True, serialize=False)),
                ('code_lieu', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('descriptif', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('sepasse', models.ManyToManyField(to='Encodage_pilote.vol')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('numerol', models.IntegerField(primary_key=True, serialize=False)),
                ('emission', models.DateField()),
                ('idpersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.personne')),
                ('idtypel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.typelicense')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idfacture', models.AutoField(primary_key=True, serialize=False)),
                ('date_facture', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('supplement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Encodage_pilote.vol')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUrgence',
            fields=[
                ('idcontact', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('estrelie', models.ManyToManyField(to='Encodage_pilote.personne')),
            ],
        ),
    ]
